// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqaqbJ1WDIkT6ZtwX2_QnUlqFnnDAqmhg',
    appId: '1:619019536671:web:93ec0677b9e3b14519082a',
    messagingSenderId: '619019536671',
    projectId: 'bacaapp-d81ba',
    authDomain: 'bacaapp-d81ba.firebaseapp.com',
    storageBucket: 'bacaapp-d81ba.firebasestorage.app',
    measurementId: 'G-T0D1LE616X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgtSozE5MNZcEjrJYWHW9H-8TSEIkAtxU',
    appId: '1:619019536671:android:1aed950007b775ad19082a',
    messagingSenderId: '619019536671',
    projectId: 'bacaapp-d81ba',
    storageBucket: 'bacaapp-d81ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr_ex9ZGV6wdaGC2t7Gpi6h1wUmOYO6UM',
    appId: '1:619019536671:ios:372eebb97be0197219082a',
    messagingSenderId: '619019536671',
    projectId: 'bacaapp-d81ba',
    storageBucket: 'bacaapp-d81ba.firebasestorage.app',
    iosBundleId: 'com.example.bacaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAr_ex9ZGV6wdaGC2t7Gpi6h1wUmOYO6UM',
    appId: '1:619019536671:ios:372eebb97be0197219082a',
    messagingSenderId: '619019536671',
    projectId: 'bacaapp-d81ba',
    storageBucket: 'bacaapp-d81ba.firebasestorage.app',
    iosBundleId: 'com.example.bacaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqaqbJ1WDIkT6ZtwX2_QnUlqFnnDAqmhg',
    appId: '1:619019536671:web:6dcff03ebe2b3fbb19082a',
    messagingSenderId: '619019536671',
    projectId: 'bacaapp-d81ba',
    authDomain: 'bacaapp-d81ba.firebaseapp.com',
    storageBucket: 'bacaapp-d81ba.firebasestorage.app',
    measurementId: 'G-QYZ852ENSZ',
  );
}
